"use client";

import Image from "next/image";
import { useState } from "react";
import ImageGalleryModal, { type GalleryItem } from "@/components/ImageGalleryModal";

const shift: GalleryItem[] = [
  { src: "/images/portfolio/illustrations/shift-01.png", alt: "Ilustración Shift" }, { src: "/images/portfolio/illustrations/shift-expansion-01.png", alt: "Ilustración Shift Expansion" }, { src: "/images/portfolio/illustrations/shift-expansion-02.png", alt: "Ilustración Shift Expansion 2" }, { src: "/images/portfolio/illustrations/shift-expansion-03.png", alt: "Ilustración Shift Expansion 3" },
];
const projects: GalleryItem[] = [{ src: "/images/portfolio/illustrations/proyecto-02.png", alt: "Ilustración Proyecto 2" }, { src: "/images/portfolio/illustrations/proyecto-03.png", alt: "Ilustración Proyecto 3" }, { src: "/images/portfolio/illustrations/proyecto-04.png", alt: "Ilustración Proyecto 4" }];
const illustrations = [...shift, ...projects];

function IllustrationTrigger({ illustration, index, className, sizes, priority, onOpen }: { illustration: GalleryItem; index: number; className?: string; sizes: string; priority?: boolean; onOpen: (index: number) => void }) { return <button type="button" className={`raw-illustration-trigger ${className ?? ""}`} onClick={() => onOpen(index)} aria-label={`Ampliar ${illustration.alt}`}><Image src={illustration.src} alt={illustration.alt} fill sizes={sizes} priority={priority} /></button>; }

export default function IllustrationGallery() { const [selected, setSelected] = useState<number | null>(null); return <section id="ilustraciones" className="raw-illustrations"><div className="raw-illustrations-intro"><div className="raw-illustrations-heading"><div><p className="raw-label">07 / Ilustración</p><h2>Ilustración.</h2></div><p>Trabajo con múltiples estilos y formatos, adaptando cada propuesta a las necesidades de cada cliente. Experiencia en producción de piezas en volumen y colaboración fluida con equipos creativos.</p></div></div><div className="raw-shift-group"><IllustrationTrigger illustration={shift[0]} index={0} className="raw-shift-hero" sizes="100vw" priority onOpen={setSelected} /><div className="raw-shift-expansions">{shift.slice(1).map((illustration, index) => <IllustrationTrigger key={illustration.src} illustration={illustration} index={index + 1} sizes="(max-width: 800px) 100vw, 31vw" onOpen={setSelected} />)}</div></div><div className="raw-illustration-project-grid">{projects.map((illustration, index) => <IllustrationTrigger key={illustration.src} illustration={illustration} index={index + shift.length} sizes="(max-width: 800px) 100vw, 31vw" onOpen={setSelected} />)}</div><div className="raw-illustrations-more"><a href="https://www.behance.net/fegav" target="_blank" rel="noreferrer">Ver más <span>↗</span></a></div>{selected !== null && <ImageGalleryModal items={illustrations} activeIndex={selected} onSelect={setSelected} onClose={() => setSelected(null)} label="Galería de ilustraciones" />}</section>; }