"use client";

import Image from "next/image";
import { useState } from "react";
import ImageGalleryModal, { type GalleryItem } from "@/components/ImageGalleryModal";

type BrandCase = { name: string; intro: string; slides: GalleryItem[] };
const cases: BrandCase[] = [
  { name: "Distrito 4271", intro: "Una identidad trabajada como sistema. Requirió investigación, identificación de problemáticas, análisis psicológico de las pretensiones de esta ONG, criterio visual y reglas claras para que cada aplicación mantenga la misma voz.", slides: [1, 2, 3, 4, 5, 6, 7].map((number) => ({ src: `/images/portfolio/manuales/identidad-4271-manual${number}.png`, alt: `Manual de Identidad 4271, lámina ${number}` })) },
  { name: "RiBuzz", intro: "Como cofundador, tuve un papel clave en la construcción de una marca sin identidad hasta convertirla en un sistema utilizable y escalable. Lideré acciones de crecimiento de marca, expansión de redes, estrategias de crecimiento, presencia en eventos y el camino para alcanzar incentivos municipales.", slides: ["", "2", "3", "4", "5", "6", "7"].map((suffix, index) => ({ src: `/images/portfolio/manuales/ribuzz${suffix}.png`, alt: `Manual RiBuzz, lámina ${index + 1}` })) },
];
function ManualSlide({ slide, onOpen, className, sizes, priority }: { slide: GalleryItem; onOpen: () => void; className?: string; sizes: string; priority?: boolean }) { return <button type="button" className={`raw-manual-slide ${className ?? ""}`} onClick={onOpen} aria-label={`Ampliar ${slide.alt}`}><Image src={slide.src} alt={slide.alt} fill sizes={sizes} priority={priority} /></button>; }
export default function ManualCases() { const [selected, setSelected] = useState<{ caseIndex: number; slideIndex: number } | null>(null); return <section id="manuales" className="raw-manuals"><div className="raw-manuals-heading"><div><p className="raw-label">06 / Impacto y concepto</p><h2>Identidades<br /><em>de marca.</em></h2><p>La identidad no termina en un logo. Cada manual reúne investigación, entendimiento del contexto y un sistema visual preparado para aplicarse con claridad y consistencia.</p></div></div><div className="raw-manual-cases">{cases.map((brandCase, caseIndex) => <article className="raw-manual-case" key={brandCase.name}><div className="raw-manual-case-intro"><p className="raw-label">Caso 0{caseIndex + 1}</p><h3>{brandCase.name}</h3><p>{brandCase.intro}</p><ol><li>Investigación</li><li>Entendimiento</li><li>Sistema visual</li><li>Aplicación</li></ol></div><ManualSlide slide={brandCase.slides[0]} onOpen={() => setSelected({ caseIndex, slideIndex: 0 })} className="raw-manual-cover" sizes="(max-width: 800px) 100vw, 62vw" priority={caseIndex === 0} /><div className="raw-manual-thumbnails">{brandCase.slides.slice(1).map((slide, index) => <ManualSlide key={slide.src} slide={slide} onOpen={() => setSelected({ caseIndex, slideIndex: index + 1 })} sizes="(max-width: 800px) 100vw, 30vw" />)}</div></article>)}</div>{selected && <ImageGalleryModal items={cases[selected.caseIndex].slides} activeIndex={selected.slideIndex} onSelect={(slideIndex) => setSelected((current) => current ? { ...current, slideIndex } : current)} onClose={() => setSelected(null)} label={`Galería ${cases[selected.caseIndex].name}`} />}</section>; }