"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Status = "Idea" | "En proceso" | "Por revisar" | "Aprobado" | "Publicado";
type Brand = { id: string; name: string; color: string };
type Item = { id: string; title: string; date: string; brandId: string; channel: string; format: string; status: Status; notes: string };
const statuses: Status[] = ["Idea", "En proceso", "Por revisar", "Aprobado", "Publicado"];
const months = ["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
const days = ["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"];
const key = "tubio-social-calendar-v1";
const starterBrands: Brand[] = [{id:"tubio",name:"TuBio",color:"#6c5ce7"},{id:"cafe",name:"Café Norte",color:"#e67e22"},{id:"alma",name:"Alma Studio",color:"#159a83"}];
const iso = (y:number,m:number,d:number) => `${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`;
function starterItems(): Item[] { const n=new Date(), y=n.getFullYear(),m=n.getMonth(); return [
{id:"1",title:"Carrusel: 5 errores de una landing",date:iso(y,m,3),brandId:"tubio",channel:"Instagram",format:"Carrusel",status:"Por revisar",notes:"Pulir el cierre y agregar CTA."},
{id:"2",title:"Reel detrás de cámaras",date:iso(y,m,7),brandId:"cafe",channel:"Instagram",format:"Reel",status:"En proceso",notes:"Falta elegir audio."},
{id:"3",title:"Caso de éxito del mes",date:iso(y,m,12),brandId:"alma",channel:"LinkedIn",format:"Post",status:"Aprobado",notes:"Programar a las 9:00 a. m."},
{id:"4",title:"Tip rápido de conversión",date:iso(y,m,18),brandId:"tubio",channel:"Instagram",format:"Historia",status:"Idea",notes:"Buscar ejemplo visual."},
{id:"5",title:"Producto de temporada",date:iso(y,m,24),brandId:"cafe",channel:"TikTok",format:"Video",status:"Publicado",notes:"Revisar métricas a las 48 h."}] }
const emptyItem=(date:string,brandId:string):Item=>({id:"",title:"",date,brandId,channel:"Instagram",format:"Post",status:"Idea",notes:""});
function Icon({name}:{name:"left"|"right"|"plus"|"calendar"|"table"|"close"|"edit"}) { const p={left:<path d="m15 18-6-6 6-6"/>,right:<path d="m9 18 6-6-6-6"/>,plus:<path d="M12 5v14M5 12h14"/>,calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,table:<><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M9 9v11"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,edit:<><path d="M12 20h9"/><path d="M16.5 3.5a2 2 0 013 3L8 18l-4 1 1-4Z"/></>}; return <svg aria-hidden="true" viewBox="0 0 24 24">{p[name]}</svg> }
const statusClass=(s:Status)=>`status-${s.toLowerCase().replaceAll(" ","-")}`;

export function SocialCalendar(){
 const now=new Date(); const [cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1)); const [brands,setBrands]=useState<Brand[]>(starterBrands); const [items,setItems]=useState<Item[]>(starterItems); const [filter,setFilter]=useState("all"); const [view,setView]=useState<"calendar"|"table">("calendar"); const [editing,setEditing]=useState<Item|null>(null); const [brandModal,setBrandModal]=useState(false); const [brandName,setBrandName]=useState(""); const [loaded,setLoaded]=useState(false);
 useEffect(()=>{const timer=window.setTimeout(()=>{try{const raw=localStorage.getItem(key);if(raw){const data=JSON.parse(raw);setBrands(data.brands);setItems(data.items)}}catch{}setLoaded(true)},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(key,JSON.stringify({brands,items}))},[brands,items,loaded]);
 const y=cursor.getFullYear(),m=cursor.getMonth(),prefix=`${y}-${String(m+1).padStart(2,"0")}`; const visible=useMemo(()=>items.filter(i=>i.date.startsWith(prefix)&&(filter==="all"||i.brandId===filter)),[items,prefix,filter]); const offset=(new Date(y,m,1).getDay()+6)%7,total=new Date(y,m+1,0).getDate(); const cells=Array.from({length:Math.ceil((offset+total)/7)*7},(_,i)=>{const d=i-offset+1;return d>0&&d<=total?d:null}); const brand=(id:string)=>brands.find(b=>b.id===id)??brands[0];
 const openNew=(day=Math.min(now.getDate(),total))=>setEditing(emptyItem(iso(y,m,day),filter==="all"?(brands[0]?.id??""):filter));
 function save(e:FormEvent){e.preventDefault();if(!editing?.title.trim())return;const value={...editing,title:editing.title.trim(),id:editing.id||crypto.randomUUID()};setItems(old=>editing.id?old.map(i=>i.id===editing.id?value:i):[...old,value]);setEditing(null)}
 function addBrand(e:FormEvent){e.preventDefault();const name=brandName.trim();if(!name)return;const palette=["#db2777","#2563eb","#65a30d","#c026d3","#0891b2"],b={id:crypto.randomUUID(),name,color:palette[brands.length%palette.length]};setBrands(v=>[...v,b]);setFilter(b.id);setBrandName("");setBrandModal(false)}
 return <div className="calendar-shell">
  <aside className="calendar-sidebar"><div className="calendar-sidebar-heading"><span>?</span><div><strong>Social Calendars</strong><small>Tu espacio de contenido</small></div></div><div className="sidebar-section"><p>Espacio de trabajo</p><button className="sidebar-active"><Icon name="calendar"/>Calendario editorial</button></div><div className="sidebar-section"><div className="sidebar-label"><p>Marcas</p><button aria-label="Añadir marca" onClick={()=>setBrandModal(true)}><Icon name="plus"/></button></div><button className={`brand-filter ${filter==="all"?"active":""}`} onClick={()=>setFilter("all")}><span className="brand-all">?</span>Todas las marcas</button>{brands.map(b=><button className={`brand-filter ${filter===b.id?"active":""}`} onClick={()=>setFilter(b.id)} key={b.id}><span style={{background:b.color}}>{b.name.slice(0,2).toUpperCase()}</span>{b.name}</button>)}</div><div className="sidebar-tip"><span>?</span><strong>Todo bajo control</strong><p>Organiza, revisa y publica el contenido de cada marca desde un solo lugar.</p></div></aside>
  <section className="calendar-workspace"><div className="calendar-titlebar"><div><p>Planificador de contenido</p><h1>{months[m]} <span>{y}</span></h1></div><button className="new-content-button" onClick={()=>openNew()}><Icon name="plus"/>Nuevo contenido</button></div>
  <div className="calendar-summary"><div><strong>{visible.length}</strong><span>Contenidos este mes</span></div>{statuses.slice(1).map(s=><div key={s}><i className={`status-dot ${statusClass(s)}`}/><strong>{visible.filter(i=>i.status===s).length}</strong><span>{s}</span></div>)}</div>
  <div className="calendar-toolbar"><div className="month-controls"><button onClick={()=>setCursor(new Date(y,m-1,1))} aria-label="Mes anterior"><Icon name="left"/></button><button onClick={()=>setCursor(new Date(now.getFullYear(),now.getMonth(),1))}>Hoy</button><button onClick={()=>setCursor(new Date(y,m+1,1))} aria-label="Mes siguiente"><Icon name="right"/></button></div><div className="view-switch"><button className={view==="calendar"?"active":""} onClick={()=>setView("calendar")}><Icon name="calendar"/>Calendario</button><button className={view==="table"?"active":""} onClick={()=>setView("table")}><Icon name="table"/>Tabla</button></div></div>
  {view==="calendar"?<div className="month-calendar"><div className="calendar-weekdays">{days.map(d=><span key={d}>{d}</span>)}</div><div className="calendar-grid">{cells.map((d,index)=>{const list=d?visible.filter(i=>i.date===iso(y,m,d)):[];const today=d===now.getDate()&&m===now.getMonth()&&y===now.getFullYear();return <div className={`calendar-day ${d?"":"empty"}`} key={index}>{d&&<><button className={`day-number ${today?"today":""}`} onClick={()=>openNew(d)}>{d}</button><div className="day-items">{list.map(i=><button className="content-chip" style={{borderLeftColor:brand(i.brandId)?.color}} onClick={()=>setEditing(i)} key={i.id}><span>{i.title}</span><small>{brand(i.brandId)?.name} · {i.format}</small></button>)}</div></>}</div>})}</div></div>:
  <div className="content-table-wrap"><table className="content-table"><thead><tr><th>Fecha</th><th>Contenido</th><th>Marca</th><th>Canal / formato</th><th>Estado</th><th/></tr></thead><tbody>{[...visible].sort((a,b)=>a.date.localeCompare(b.date)).map(i=><tr key={i.id}><td>{new Date(`${i.date}T12:00:00`).toLocaleDateString("es-CO",{day:"2-digit",month:"short"})}</td><td><strong>{i.title}</strong><small>{i.notes||"Sin notas"}</small></td><td><span className="table-brand" style={{color:brand(i.brandId)?.color}}>{brand(i.brandId)?.name}</span></td><td>{i.channel}<small>{i.format}</small></td><td><span className={`status-pill ${statusClass(i.status)}`}>{i.status}</span></td><td><button className="edit-row" onClick={()=>setEditing(i)}><Icon name="edit"/></button></td></tr>)}</tbody></table>{!visible.length&&<div className="calendar-empty"><span>?</span><h2>Este mes está listo para tus ideas</h2><p>Crea el primer contenido o cambia de marca.</p><button onClick={()=>openNew()}>Añadir contenido</button></div>}</div>}</section>
 {editing&&<div className="calendar-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setEditing(null)}><div className="calendar-modal" role="dialog" aria-modal="true"><button className="modal-close" aria-label="Cerrar" onClick={()=>setEditing(null)}><Icon name="close"/></button><p className="modal-kicker">Contenido editorial</p><h2>{editing.id?"Editar contenido":"Nueva publicación"}</h2><form onSubmit={save}><label className="field-wide">Título<input autoFocus required value={editing.title} onChange={e=>setEditing({...editing,title:e.target.value})} placeholder="¿Qué vamos a publicar?"/></label><label>Fecha<input required type="date" value={editing.date} onChange={e=>setEditing({...editing,date:e.target.value})}/></label><label>Marca<select value={editing.brandId} onChange={e=>setEditing({...editing,brandId:e.target.value})}>{brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select></label><label>Canal<select value={editing.channel} onChange={e=>setEditing({...editing,channel:e.target.value})}>{["Instagram","TikTok","LinkedIn","Facebook","YouTube","Blog"].map(v=><option key={v}>{v}</option>)}</select></label><label>Formato<select value={editing.format} onChange={e=>setEditing({...editing,format:e.target.value})}>{["Post","Carrusel","Reel","Historia","Video","Artículo"].map(v=><option key={v}>{v}</option>)}</select></label><label className="field-wide">Estado<select value={editing.status} onChange={e=>setEditing({...editing,status:e.target.value as Status})}>{statuses.map(v=><option key={v}>{v}</option>)}</select></label><label className="field-wide">Notas y elementos a pulir<textarea rows={4} value={editing.notes} onChange={e=>setEditing({...editing,notes:e.target.value})} placeholder="Pendientes, ideas, CTA, recursos..."/></label><div className="modal-actions">{editing.id&&<button className="delete-button" type="button" onClick={()=>{setItems(v=>v.filter(i=>i.id!==editing.id));setEditing(null)}}>Eliminar</button>}<button className="cancel-button" type="button" onClick={()=>setEditing(null)}>Cancelar</button><button className="save-button">Guardar contenido</button></div></form></div></div>}
 {brandModal&&<div className="calendar-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setBrandModal(false)}><div className="calendar-modal brand-modal"><button className="modal-close" aria-label="Cerrar" onClick={()=>setBrandModal(false)}><Icon name="close"/></button><p className="modal-kicker">Tu espacio de trabajo</p><h2>Añadir una marca</h2><form onSubmit={addBrand}><label className="field-wide">Nombre de la marca<input autoFocus required value={brandName} onChange={e=>setBrandName(e.target.value)} placeholder="Ej. Casa Bonita"/></label><div className="modal-actions"><button className="cancel-button" type="button" onClick={()=>setBrandModal(false)}>Cancelar</button><button className="save-button">Crear marca</button></div></form></div></div>}
 </div>
}