import Image from "next/image";
import Link from "next/link";

export const metadata = {
  title: "Portafolio | Felipe RamÃ­rez",
  description: "Portafolio creativo de Felipe RamÃ­rez: estrategia, identidad, ilustraciÃ³n y producciÃ³n audiovisual.",
};

const disciplines = [{ name: "Illustration", href: "#proyecto-4" }, { name: "Presentation", href: "#proyecto-2" }, { name: "Typography", href: "#proyecto-3" }, { name: "Branding", href: "#proyecto-2" }, { name: "Art Direction", href: "#proyecto-3" }, { name: "Layout", href: "#proyecto-1" }, { name: "Logo Design", href: "#proyecto-2" }, { name: "UI Design", href: "#proyecto-1" }];
const projects = ["ProducciÃ³n audiovisual", "Estrategia de marca", "Impacto y concepto", "IlustraciÃ³n"];

export default function PortfolioPage() {
  return (
    <main id="inicio" className="raw-portfolio">
      <header className="raw-portfolio-header"><Link href="/">TuBio</Link><nav><a href="#sobre-mi">Sobre mÃ­</a><a href="#trabajo">Trabajo</a><a href="#contacto">Contacto</a></nav><span>2026 / Portfolio</span></header>
      <a className="raw-whatsapp-float" href="https://wa.me/573004318932" target="_blank" rel="noreferrer" aria-label="Escribir a Felipe por WhatsApp">
        <Image src="/images/portfolio/whatsapp.webp" alt="" width={56} height={56} />
      </a>
      <section className="raw-portfolio-hero"><div className="raw-hero-top"><div><p className="raw-date">25 Jul, 2026</p><p className="raw-person">Felipe Gaviria VÃ¡squez</p></div><p className="raw-contact-data">MedellÃ­n, Colombia</p></div><div className="raw-hero-title"><div className="raw-role-title"><span>Estrategia de marca&nbsp;&nbsp; / &nbsp;&nbsp;DirecciÃ³n creativa&nbsp;&nbsp; / &nbsp;&nbsp;ProducciÃ³n audiovisual</span><a href="mailto:felipegaviria17@hotmail.com">felipegaviria17@hotmail.com</a></div><h1>Portafolio</h1></div><a className="raw-scroll-cue" href="#sobre-mi">Desplazar para explorar <b>â†“</b></a></section>
      <section id="sobre-mi" className="raw-intro"><div className="raw-about-heading"><div><p className="raw-label">01 / Sobre mÃ­</p><h2>Hola,<br /><em>soy Felipe.</em></h2></div><div className="raw-pfp-frame"><Image src="/images/portfolio/pfp.jpeg" alt="Felipe Gaviria VÃ¡squez" fill sizes="(max-width: 700px) 160px, 220px" /></div></div><p className="raw-about-role">MedellÃ­n, Colombia. Ingeniero en DiseÃ±o de Entretenimiento Digital. / Estratega de Marca.</p><div className="raw-intro-subtitle"><p className="raw-label">Lo que hago</p><h3>y me gusta hacer.</h3></div><div className="raw-intro-grid"><p>Trabajo entre la estrategia, la sensibilidad visual y la producciÃ³n. Me interesa encontrar la idea que ordena un proyecto y convertirla en algo que se pueda ver, sentir y recordar.</p><p>Este portafolio reÃºne algunas de las mÃ¡s recientes exploraciones, donde seguimos aprendiendo, creando experiencias y transformando.</p></div><div className="raw-side-skills"><span>Illustration</span><span>Presentation</span><span>Typography</span><span>Branding</span><span>Art Direction</span><span>Layout</span><span>Logo Design</span><span>UI Design</span></div></section>
      <section className="raw-experience"><p className="raw-label">02 / DÃ³nde he trabajado</p><h2>Experiencia.</h2><div className="raw-experience-list"><article><span className="raw-experience-number">01</span><div><p className="raw-experience-role">ProducciÃ³n audiovisual</p><h3>MERO STUDIO SAS <small>(2023 â€” 2026)</small></h3><p>IlustraciÃ³n de escenarios y personajes 2D, ediciÃ³n de videos, storytelling y direcciÃ³n de arte.</p><strong>Clientes atendidos por mÃ­</strong><p>Chef Burger Â· Pentatonic Â· Frank Sinatra (representaciÃ³n), etc.</p></div></article><article><span className="raw-experience-number">02</span><div><p className="raw-experience-role">Independiente</p><h3>@FEGAV_ART <small>(2020 â€” 2024)</small></h3><p>IlustraciÃ³n de fanart, concept art para empresas, videojuegos, diseÃ±o e ilustraciÃ³n de personajes para cÃ³mics y pÃºblico interesado.</p></div></article><article><span className="raw-experience-number">03</span><div><p className="raw-experience-role">DiseÃ±o grÃ¡fico</p><h3>ROTARY INTERNATIONAL <small>(2018 â€” 2026)</small></h3><p>IlustraciÃ³n de logotipos y banners en planeaciÃ³n de eventos de alta participaciÃ³n social. Manejo de redes sociales y branding.</p></div></article><article><span className="raw-experience-number">04</span><div><p className="raw-experience-role">DiseÃ±o grÃ¡fico</p><h3>+MELO AGENCY <small>(2024)</small></h3><p>IlustraciÃ³n y ediciÃ³n de piezas estÃ¡ticas y algunos reels. AcompaÃ±amiento de mÃ©tricas de marca y carruseles. Manejo de redes sociales y branding.</p></div></article><article><span className="raw-experience-number">05</span><div><p className="raw-experience-role">Ilustrador</p><h3>GLOBAL GAME JAM PJ. <small>(2023, 2025)</small></h3><p>DiseÃ±o de UX y UI. IlustraciÃ³n de fondos y diseÃ±o Ã³ptimo para animaciÃ³n.</p></div></article><article><span className="raw-experience-number">06</span><div><p className="raw-experience-role">Ilustrador</p><h3>FORJA STUDIOS</h3><p>IlustraciÃ³n de fondos y diseÃ±o Ã³ptimo para animaciÃ³n. ComposiciÃ³n de ambientes y teorÃ­a de espacios y colores.</p></div></article><article><span className="raw-experience-number">07</span><div><p className="raw-experience-role">Emprendedor + direcciÃ³n creativa</p><h3>RIBUZZ <small>(2025 â€” 2026)</small></h3><p>EdiciÃ³n consistente de carruseles y piezas para redes. Estrategia de empresas, branding y business model canvas.</p></div></article></div></section>
      <section className="raw-tools"><p className="raw-label">03 / Herramientas</p><h2>Â¿QuÃ© herramientas<br /><em>me acompaÃ±an?</em></h2><p>After Effects Â· Reaper Audio Â· Photoshop Â· Illustrator Â· Unity Â· Blender Â· Canva</p></section><section id="trabajo" className="raw-disciplines"><p className="raw-label">04 / Lo que vas a encontrar aquÃ­</p><div className="raw-discipline-list">{disciplines.map((item, index) => <div key={item.name}><span>0{index + 1}</span><h3>{item.name}</h3><a href={item.href} aria-label={`Ir a ${item.name}`}>â†—</a></div>)}</div></section>
      {projects.map((project, index) => <section id={`proyecto-${index + 1}`} className={`raw-project-section raw-project-section-${index + 1}`} key={project}><p className="raw-label">0{index + 6} / Proyecto</p><h2>{project}</h2><p>Esta secciÃ³n queda preparada para desarrollar el proyecto, sus imÃ¡genes, proceso, resultados y detalles.</p><a href="#trabajo">Volver a ramas <span>â†—</span></a></section>)}<section id="contacto" className="raw-contact"><p className="raw-label">10 / Siguiente proyecto</p><h2>Conversemos<br /><em>algo chÃ©vere.</em></h2><a className="raw-whatsapp-link" href="https://wa.me/573004318932" target="_blank" rel="noreferrer"><Image className="raw-whatsapp-icon" src="/images/portfolio/whatsapp.webp" alt="" width={28} height={28} /> WhatsApp <small>+57 3004318932</small></a></section>
      <footer className="raw-portfolio-footer"><span>Felipe Gaviria VÃ¡squez</span><a href="#inicio">Volver arriba</a><span>Colombia / 2026</span></footer>
    </main>
  );
}