import Image from "next/image";
import Link from "next/link";
import IllustrationGallery from "@/components/IllustrationGallery";

export const metadata = {
  title: "Portafolio | Felipe Ramírez",
  description: "Portafolio creativo de Felipe Ramírez: estrategia, identidad, ilustración y producción audiovisual.",
};

const projects = ["Producción audiovisual", "Estrategia de marca", "Impacto y concepto"];
const tools = ["After Effects", "Reaper Audio", "Photoshop", "Illustrator", "Unity", "Blender", "Canva", "CapCut"];

export default function PortfolioPage() {
  return (
    <main id="inicio" className="raw-portfolio">
      <a className="raw-whatsapp-float" href="https://wa.me/573004318932" target="_blank" rel="noreferrer" aria-label="Escribir a Felipe por WhatsApp">
        <Image src="/images/portfolio/whatsapp.webp" alt="" width={56} height={56} />
      </a>
      <section className="raw-portfolio-hero"><div className="raw-hero-top"><div><p className="raw-date">25 Jul, 2026</p><p className="raw-person">Felipe Gaviria Vásquez</p></div><p className="raw-contact-data">Medellín, Colombia</p></div><div className="raw-hero-title"><div className="raw-role-title"><span>Estrategia de marca&nbsp;&nbsp; / &nbsp;&nbsp;Dirección creativa&nbsp;&nbsp; / &nbsp;&nbsp;Producción audiovisual</span><a href="mailto:felipegaviria17@hotmail.com">felipegaviria17@hotmail.com</a></div><h1>Portafolio</h1></div><a className="raw-scroll-cue" href="#sobre-mi">Desplazar para explorar <b>↓</b></a></section>
      <section id="sobre-mi" className="raw-intro"><div className="raw-about-heading"><div><p className="raw-label">01 / Sobre mí</p><h2>Hola,<br /><em>soy Felipe.</em></h2></div><div className="raw-pfp-frame"><Image src="/images/portfolio/pfp.jpeg" alt="Felipe Gaviria Vásquez" fill sizes="(max-width: 700px) 160px, 220px" /></div></div><p className="raw-about-role">Medellín, Colombia. Ingeniero en Diseño de Entretenimiento Digital. / Estratega de Marca.</p><div className="raw-intro-subtitle"><p className="raw-label">Lo que hago</p><h3>y me gusta hacer.</h3></div><div className="raw-intro-grid"><p>Trabajo entre la estrategia, la sensibilidad visual y la producción. Me interesa encontrar la idea que ordena un proyecto y convertirla en algo que se pueda ver, sentir y recordar.</p><p>Este portafolio reúne algunas de las más recientes exploraciones, donde seguimos aprendiendo, creando experiencias y transformando.</p></div><div className="raw-side-skills"><span>Ilustración</span><span>Presentaciones</span><span>Tipografía</span><span>Identidad de marca</span><span>Dirección de arte</span><span>Maquetación</span><span>Diseño de logos</span><span>Diseño UI</span></div></section>
      <section className="raw-experience"><div className="raw-experience-heading"><p className="raw-label">02 / Dónde he trabajado</p><h2>Experiencia.</h2></div><div className="raw-experience-list"><article><div><p className="raw-experience-role">Producción audiovisual</p><h3>MERO STUDIO SAS <small>(2023 — 2026)</small></h3><p>Ilustración de escenarios y personajes 2D, edición de videos, storytelling y dirección de arte.</p><strong>Clientes atendidos por mí</strong><p>Chef Burger · Pentatonic · Frank Sinatra (representación), etc.</p></div></article><article><div><p className="raw-experience-role">Independiente</p><h3>@FEGAV_ART <small>(2020 — 2024)</small></h3><p>Ilustración de fanart, concept art para empresas, videojuegos, diseño e ilustración de personajes para cómics y público interesado.</p></div></article><article><div><p className="raw-experience-role">Diseño gráfico</p><h3>ROTARY INTERNATIONAL <small>(2018 — 2026)</small></h3><p>Ilustración de logotipos y banners en planeación de eventos de alta participación social. Manejo de redes sociales y branding.</p></div></article><article><div><p className="raw-experience-role">Diseño gráfico</p><h3>+MELO AGENCY <small>(2024)</small></h3><p>Ilustración y edición de piezas estáticas y algunos reels. Acompañamiento de métricas de marca y carruseles. Manejo de redes sociales y branding.</p></div></article><article><div><p className="raw-experience-role">Ilustrador</p><h3>GLOBAL GAME JAM PJ. <small>(2023, 2025)</small></h3><p>Diseño de UX y UI. Ilustración de fondos y diseño óptimo para animación.</p></div></article><article><div><p className="raw-experience-role">Ilustrador</p><h3>FORJA STUDIOS</h3><p>Ilustración de fondos y diseño óptimo para animación. Composición de ambientes y teoría de espacios y colores.</p></div></article><article><div><p className="raw-experience-role">Emprendedor + dirección creativa</p><h3>RIBUZZ <small>(2025 — 2026)</small></h3><p>Edición consistente de carruseles y piezas para redes. Estrategia de empresas, branding y business model canvas.</p></div></article></div></section>
      <section className="raw-tools"><p className="raw-label">03 / Herramientas</p><h2>¿Qué herramientas<br /><em>me acompañan?</em></h2><div className="raw-tool-list">{tools.map((tool) => <span key={tool}>{tool}</span>)}</div></section>
      {projects.map((project, index) => <section id={`proyecto-${index + 1}`} className={`raw-project-section raw-project-section-${index + 1}`} key={project}><p className="raw-label">0{index + 4} / Proyecto</p><h2>{project}</h2><p>Esta sección queda preparada para desarrollar el proyecto, sus imágenes, proceso, resultados y detalles.</p><a href="#inicio">Volver arriba <span>↗</span></a></section>)}
      <IllustrationGallery />
      <section id="contacto" className="raw-contact"><p className="raw-label">08 / Siguiente proyecto</p><h2>Creemos<br /><em>algo que valga.</em></h2><div className="raw-contact-actions"><a className="raw-whatsapp-link" href="https://wa.me/573004318932" target="_blank" rel="noreferrer"><span>Escríbeme</span><Image className="raw-whatsapp-icon" src="/images/portfolio/whatsapp.webp" alt="" width={28} height={28} /></a><a className="raw-email-link" href="mailto:felipegaviria17@hotmail.com" aria-label="Escribir a Felipe por correo"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="5" width="18" height="14" rx="1" /><path d="m4 7 8 6 8-6" /></svg></a></div></section>
      <footer className="raw-portfolio-footer"><span>Felipe Gaviria Vásquez</span><a href="#inicio">Volver arriba</a><span>Colombia / 2026</span></footer>
    </main>
  );
}